# Generated by Django 4.0.4 on 2022-05-21 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('name', models.CharField(default='guest', max_length=30, verbose_name='name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('language', models.CharField(choices=[('cn', 'Simplified Chinese'), ('jp', 'Japanese'), ('fa', 'Persian'), ('es', 'Spanish'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('tr', 'Turkish'), ('ko', 'Korean'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('id', 'Indonesian'), ('nl', 'Dutch')], default='fa', max_length=2, verbose_name='language')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtext', models.CharField(default='', max_length=100)),
                ('Atext', models.CharField(default='', max_length=30)),
                ('CERF', models.CharField(default='', max_length=2)),
                ('morph', models.CharField(default='', max_length=100)),
                ('succeed', models.FloatField(default=1)),
                ('reviewed', models.IntegerField(default=1)),
                ('ansrate', models.FloatField(default=1)),
                ('data_created', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='card_user_likes', through='backend.LikeTable', to=settings.AUTH_USER_MODEL)),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Qtext', 'Atext')},
            },
        ),
        migrations.CreateModel(
            name='ShareTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shared', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sencard')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=100)),
                ('reads', models.ManyToManyField(related_name='card_user_reads', through='backend.ReadTable', to='backend.sencard')),
                ('saves', models.ManyToManyField(related_name='card_user_saves', through='backend.SaveTable', to='backend.sencard')),
                ('shares', models.ManyToManyField(related_name='card_user_shares', through='backend.ShareTable', to='backend.sencard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sharetable',
            name='userProf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile'),
        ),
        migrations.AddField(
            model_name='savetable',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sencard'),
        ),
        migrations.AddField(
            model_name='savetable',
            name='userProf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile'),
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('date_reported', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sencard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readtable',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sencard'),
        ),
        migrations.AddField(
            model_name='readtable',
            name='userProf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile'),
        ),
        migrations.AddField(
            model_name='liketable',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sencard'),
        ),
        migrations.AddField(
            model_name='liketable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EnWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(default='', max_length=30)),
                ('pos', models.CharField(default='', max_length=4)),
                ('CERF', models.CharField(default='OL', max_length=2)),
                ('freq', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'unique_together': {('stem', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='TrSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sharetable',
            unique_together={('userProf', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='savetable',
            unique_together={('userProf', 'card')},
        ),
        migrations.CreateModel(
            name='RuSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='readtable',
            unique_together={('userProf', 'card')},
        ),
        migrations.CreateModel(
            name='PtSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NlSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='liketable',
            unique_together={('user', 'card')},
        ),
        migrations.CreateModel(
            name='KoSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JpSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IdSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='HiSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FrSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FaSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EsSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DeSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CnSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BnSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(default=0)),
                ('ensent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ensent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ensent', 'user')},
            },
        ),
    ]
